/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joanchen' at '1/25/16 4:16 PM' with Gradle 2.4
 *
 * @author joanchen, @date 1/25/16 4:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
